# Generated by Django 4.0.1 on 2022-01-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='작성날짜')),
                ('writer', models.CharField(max_length=20, verbose_name='작성자')),
                ('body', models.CharField(max_length=100, verbose_name='내용')),
            ],
        ),
    ]
